# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e3eea440e8aeea844f279926550f43de8a397438ced0c15cf09e0d331e194b916e6f7d7319debec9d1a51490c988d163a0508598199c10a521cf9aa5fffba7

test:
  secret_key_base: c780d35701c3286135b0353f94e2e9ba9a9e483111f9d6fbd427927f39ba85fea8ad5d921496826f05ca9948774f84ba050de8e0f3906434075811c9309192af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
